package net.matsudamper.dsl.element

enum class Complication(private val value: String) {
    MONOCHROMATIC_IMAGE("MONOCHROMATIC_IMAGE"),
    MONOCHROMATIC_IMAGE_AMBIENT("MONOCHROMATIC_IMAGE_AMBIENT"),
    TEXT("TEXT"),
    TITLE("TITLE"),
    PHOTO_IMAGE("PHOTO_IMAGE"),
    RANGED_VALUE_MIN("RANGED_VALUE_MIN"),
    RANGED_VALUE_MAX("RANGED_VALUE_MAX"),
    RANGED_VALUE_VALUE("RANGED_VALUE_VALUE"),
    RANGED_VALUE_COLORS("RANGED_VALUE_COLORS"),
    RANGED_VALUE_COLORS_INTERPOLATED("RANGED_VALUE_COLORS_INTERPOLATED"),
    SMALL_IMAGE("SMALL_IMAGE"),
    SMALL_IMAGE_AMBIENT("SMALL_IMAGE_AMBIENT"),
    IMAGE_STYLE("IMAGE_STYLE"),
    GOAL_PROGRESS_VALUE("GOAL_PROGRESS_VALUE"),
    GOAL_PROGRESS_TARGET_VALUE("GOAL_PROGRESS_TARGET_VALUE"),
    GOAL_PROGRESS_COLORS("GOAL_PROGRESS_COLORS"),
    GOAL_PROGRESS_COLORS_INTERPOLATE("GOAL_PROGRESS_COLORS_INTERPOLATE"),
    WEIGHTED_ELEMENTS_COLORS("WEIGHTED_ELEMENTS_COLORS"),
    WEIGHTED_ELEMENTS_WEIGHTS("WEIGHTED_ELEMENTS_WEIGHTS"),
    WEIGHTED_ELEMENTS_BACKGROUND_COLOR("WEIGHTED_ELEMENTS_BACKGROUND_COLOR"),
    ;

    fun getSymbol(): String = "COMPLICATION.$value"

    override fun toString(): String {
        return getSymbol()
    }
}