name: Build Check
on:
  pull_request:
    types: [ opened, reopened ]

  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.workers.max=4 -Dorg.gradle.jvmargs=-Xmx13g
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: build
        run: ./gradlew assembleDebug
